# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  repositories:
    # Required for litmus
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'git://github.com/puppetlabs/provision.git'

    # Other dependencies
    disks: 'https://code.immerda.ch/immerda/puppet-modules/disks'
    podman: 'git://github.com/duritong/puppet-podman.git'
    selinux: 'https://code.immerda.ch/immerda/puppet-modules/selinux'
    user: 'https://code.immerda.ch/immerda/puppet-modules/user'
  forge_modules:
    concat: "puppetlabs/concat"
    lvm: "puppetlabs/lvm"
    mount_core: "puppetlabs/mount_core"
    stdlib: "puppetlabs/stdlib"
    sysctl: "duritong/sysctl"
