---
.travis.yml:
  includes:
    -
      bundler_args:
      env: PLATFORMS=centos7
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, waffleimage/centos7]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
    -
      bundler_args:
      env: PLATFORMS=centos8
      rvm: 2.5.3
      before_script:
        - bundle exec rake 'litmus:provision[docker, camptocamp/litmus_centos:8]'
        - bundle exec rake 'litmus:install_agent[puppet5]'
        - bundle exec rake litmus:install_module
      script:
        - bundle exec rake litmus:acceptance:parallel
      services: docker
      stage: acceptance
      sudo: required
  branches:
    - master
    - /^\d/
  deploy_to_forge:
    enabled: true
    tag_regex: "^\\d"

Gemfile:
  optional:
    ':development':
      - gem: 'github_changelog_generator'
Rakefile:
  changelog_version_tag_pattern: '%s'
